# Generated by Django 5.0.6 on 2024-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок объявления')),
                ('id_number', models.PositiveIntegerField(verbose_name='id объявления')),
                ('author', models.CharField(max_length=200, verbose_name='Автор объявления')),
                ('viewing', models.PositiveIntegerField(verbose_name='Просмотры объявления')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_check', models.DateTimeField(auto_now_add=True, verbose_name='Дата последней проверки')),
            ],
        ),
    ]
